# Generated by Django 3.2.7 on 2021-09-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('amont', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=100)),
            ],
        ),
    ]
